package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "Tutorial00_Basic",
    srcs = [
        'Tutorial00_Basic.cpp'
    ],
    deps = [
      '//subprojects/ogre2/OgreMain',
      '//subprojects/ogre2/Components/Hlms/Unlit',
      '//subprojects/ogre2/Components/Hlms/Pbs',
    ],
  )
