package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Common",
    srcs = [
      'src/OgreHlmsBufferManager.cpp',
    ],
    hdrs = [
      'include/OgreHlmsBufferManager.h',
      'include/OgreHlmsTextureBaseClass.h',
      'include/OgreHlmsTextureBaseClass.inl',
    ],
    includes = [
        'include',
    ],
  deps = [
    '//subprojects/ogre2/OgreMain'
  ],
)

cc_library(
    name = "HlmsCommon",
    srcs = [
      'src/OgreHlmsBufferManager.cpp',
    ],
    hdrs = [
      'include/OgreHlmsBufferManager.h',
      'include/OgreHlmsTextureBaseClass.h',
      'include/OgreHlmsTextureBaseClass.inl',
    ],
    includes = [
        'include',
    ],
  deps = [
    '//subprojects/ogre2/OgreMain'
  ],
)
